services:

  db:
    image: mysql:8.0

    container_name: decors_mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]

      interval: 10s
      timeout: 5s
      retries: 10


  web:
    build: .

    container_name: decors_web

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs


volumes:
  mysql_data:
  static_volume:
  media_volume:
  logs_volume: